//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp.Model.EFSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineExamAppDBEntities3 : DbContext
    {
        public OnlineExamAppDBEntities3()
            : base("name=OnlineExamAppDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExamDetail> ExamDetails { get; set; }
        public virtual DbSet<ProposedAnswer> ProposedAnswers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual DbSet<QuestionProposedAnswer> QuestionProposedAnswers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserResponseDetail> UserResponseDetails { get; set; }
        public virtual DbSet<UserResponseHeader> UserResponseHeaders { get; set; }
    }
}
