//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp.Model.EFSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResponseHeader
    {
        public UserResponseHeader()
        {
            this.UserResponseDetails = new HashSet<UserResponseDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<System.DateTime> AttemptedOn { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserResponseDetail> UserResponseDetails { get; set; }
    }
}
